### PR TITLE
Release 2.0.1

### PR DESCRIPTION
**Pull request by GuilhE**
# Changelog
## Fork 2.0.1
- Removed `fun saveDir(path: String): Builder` and `fun saveDir(file: File): Builder`

---
## Fork 2.0.0
- `CompressionProvider.kt` logic refactor
- Removed `fun compress(maxSize: Int): Builder` since it was comparing the size of the file and not the image (and the resize operation is enough);
- Image maxResultSize (resize) algorithm refactor: `fun maxResultSize(width: Int, height: Int, keepRatio: Boolean = false): Builde`;
- Replaced AsyncTask with coroutines

---

## Fork 1.9.1
- Removed all `sstartActivityForResult` from library since caller is responsible to provide an `ActivityResultLauncher<Intent>`
- Removed https://github.com/florent37/InlineActivityResult dependency

---

## Fork 1.9.0
- Added [Android Activity Result APIs](https://developer.android.com/training/basics/intents/result)

### CODE REVIEW

**Comment by Dhaval2404** [comment]
@GuilhE Can you please resolve the conflict? I will merge your changes after that.

Extremely sorry for the late reply. You have done great work. Thank you so much.

**Comment by GuilhE** [comment]
@Dhaval2404 done

**Comment by LevisLuong** [comment]
Hi @GuilhE ! Does this update include fix for warning using requestLegacyExternalStorage on android 11, when upload to play store ?

**Comment by GuilhE** [comment]
@LevisLuong yes, in 2.0.0 it was fixed, but I forgot to remove the `saveDir` method which could lead to that problem.
The sample app doesn't have `requestLegacyExternalStorage`

**Comment by LevisLuong** [comment]
@GuilhE  I have checked and tried to run with your 2.0.1 version in Android 10. But I got this error:
`2021-04-27 15:32:43.157 17291-17291/com.github.dhaval2404.imagepicker.sample W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cc463f5
2021-04-27 15:32:44.470 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err: java.io.IOException: Permission denied
2021-04-27 15:32:44.475 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2021-04-27 15:32:44.475 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
2021-04-27 15:32:44.476 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at java.io.File.createNewFile(File.java:1008)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.github.dhaval2404.imagepicker.util.FileUtil.getImageFile(FileUtil.kt:47)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.github.dhaval2404.imagepicker.util.FileUtil.getImageFile$default(FileUtil.kt:31)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.github.dhaval2404.imagepicker.provider.CameraProvider.startCameraIntent(CameraProvider.kt:119)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.github.dhaval2404.imagepicker.provider.CameraProvider.onRequestPermissionsResult(CameraProvider.kt:138)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.github.dhaval2404.imagepicker.ImagePickerActivity.onRequestPermissionsResult(ImagePickerActivity.kt:137)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.Activity.dispatchRequestPermissionsResult(Unknown Source:27)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.Activity.dispatchActivityResult(Unknown Source:38)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.ActivityThread.deliverResults(Unknown Source:44)
2021-04-27 15:32:44.479 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.ActivityThread.handleSendResult(Unknown Source:156)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(Unknown Source:11)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.os.Handler.dispatchMessage(Unknown Source:19)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.os.Looper.loop(Unknown Source:242)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at android.app.ActivityThread.main(Unknown Source:98)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
2021-04-27 15:32:44.480 17291-17291/com.github.dhaval2404.imagepicker.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(Unknown Source:275)`

Could you please help me check if It can run on Android from your side. thanks

**Comment by GuilhE** [comment]
See if this [thread](https://github.com/Dhaval2404/ImagePicker/pull/171) helps

**Comment by Drjacky** [comment]
⚠️ @Dhaval2404 & @GuilhE Please check Gallery on API 29, before merging this PR. ⚠️

**Pull request closed without merging**
