### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by GuilhE**
# Changelog

## Fork 2.0.0
- `CompressionProvider.kt` logic refactor
- Removed `fun compress(maxSize: Int): Builder` since it was comparing the size of the file and not the image (and the resize operation is enough);
- Image maxResultSize (resize) algorithm refactor: `fun maxResultSize(width: Int, height: Int, keepRatio: Boolean = false): Builde`;
- Replaced AsyncTask with coroutines

---

## Fork 1.9.1
- Removed all `sstartActivityForResult` from library since caller is responsible to provide an `ActivityResultLauncher<Intent>`
- Removed https://github.com/florent37/InlineActivityResult dependency

---

## Fork 1.9.0
- Added [Android Activity Result APIs](https://developer.android.com/training/basics/intents/result)

### CODE REVIEW

**Comment by costular** [comment]
@Dhaval2404 could you check this please? On May 5th Google will start removing apps from Play Store which use legacy storage

**Comment by Drjacky** [comment]
@GuilhE But in your version (release-2.0.0), the sample app `compileSdkVersion` and `targetSdkVersion` are not 30.
And if you set it to 30, even if you add
```xml
<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
</queries>
```
It still shows the error:
> Failed to create Camera image file

**Comment by GuilhE** [comment]
> @GuilhE But in your version (release-2.0.0), the sample app `compileSdkVersion` and `targetSdkVersion` are not 30.
> And if you set it to 30, even if you add
> 
> ```
> <queries>
>         <intent>
>             <action android:name="android.media.action.IMAGE_CAPTURE" />
>         </intent>
> </queries>
> ```
> 
> It still shows the error:
> 
> > Failed to create Camera image file


I'm using the following configuration in a project and it works with Pixel 3a running Android 11 
```
object AndroidConstants {
    const val minSdkVersion = 24
    const val targetSdkVersion = 30
    const val compileSdkVersion = 30
    const val buildToolsVersion = "30.0.2"
}
```

But then I've found out that I've a merged manifest with:
`<application android:requestLegacyExternalStorage="true">`

So that's why it's working...  🤔 I'll dig into it as soon as possible.

**Comment by GuilhE** [comment]
@Drjacky ok quick update, I've removed that import and know there's no ` <application android:requestLegacyExternalStorage="true">` and it works... Do you declare any file provider?

```
<application>
        <!--Providers-->
        <provider
            android:name=".utils.AppFileProvider"
            android:authorities="${applicationId}.files.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
    </application>
```

**Comment by Drjacky** [comment]
@GuilhE 
library's AndroidManifest.xml:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.imagepicker">

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <application>

        <activity
            android:name="com.example.imagepicker.ImagePickerActivity"
            android:screenOrientation="unspecified"
            android:theme="@style/Theme.Transparent.ImagePicker" />

        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />

        <provider
            android:name="com.example.imagepicker.ImagePickerFileProvider"
            android:authorities="${applicationId}.imagepicker.provider"
            android:exported="false"
            android:grantUriPermissions="true">

            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/image_picker_provider_paths" />

        </provider>

    </application>

</manifest>

```

Sample app's AndroidManifest:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.imagepicker.sample">

    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:fullBackupContent="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name="com.example.imagepicker.sample.MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by Drjacky** [comment]
@GuilhE Please use this sample app: https://github.com/GuilhE/ImagePicker/tree/release-2.0.0/sample
And set the targetSdk and compileSdk to 30, and you will see the error.

**Comment by GuilhE** [comment]
@Drjacky comment this [line](https://github.com/GuilhE/ImagePicker/blob/c4307fd64cd4594f9fcca318948c3737758232a3/sample/src/main/kotlin/com.github.dhaval2404.imagepicker/sample/MainActivity.kt#L121) and it will work. I'll remove it from the sample.

**Comment by GuilhE** [comment]
@Drjacky new [PR](https://github.com/Dhaval2404/ImagePicker/pull/195) to avoid this problem.

**Comment by Drjacky** [comment]
@GuilhE On this [PR](https://github.com/Dhaval2404/ImagePicker/pull/195) please try to choose the image from Gallery - On Emulator API 30

**Comment by GuilhE** [comment]
> @GuilhE On this [PR](https://github.com/Dhaval2404/ImagePicker/pull/195) please try to choose the image from Gallery - On Emulator API 30

Screenshot 2021-04-21 at 18 32 02 Screenshot 2021-04-21 at 18 32 12 Screenshot 2021-04-21 at 18 32 22 Screenshot 2021-04-21 at 18 32 35

**Comment by Drjacky** [comment]
> > @GuilhE On this [PR](https://github.com/Dhaval2404/ImagePicker/pull/195) please try to choose the image from Gallery - On Emulator API 30
> 
> Created a new AVD with API 30, took a picture with camera, and then used the app to import from Gallery, it worked 🤔
> 
> Screenshot 2021-04-21 at 18 32 02 Screenshot 2021-04-21 at 18 32 12 Screenshot 2021-04-21 at 18 32 22 Screenshot 2021-04-21 at 18 32 35

You're right. with that scenario, it shows the taken picture.
What I did was, uploading a picture to the emulator in these folders:
`sdcard -> DCIM -> HERE`, `sdcard -> DCIM -> Camera -> HERE`, `sdcard -> Download -> HERE`, `sdcard -> Pictures -> HERE`, `storage -> emulated -> 0 -> DCIM -> HERE`, `storage -> emulated -> 0 -> DCIM -> Camera -> HERE`, `storage -> emulated -> 0 -> Download -> HERE`, `storage -> emulated -> 0 -> Pictures -> HERE`, `storage -> 19F9-2A14 -> DCIM -> HERE`, `storage -> 19F9-2A14 -> DCIM -> Camera -> HERE`, `storage -> 19F9-2A14 -> Download -> HERE`, `storage -> 19F9-2A14 -> Pictures -> HERE`.

And in the app, when I pressed Gallery, none of them had been listed!

**Comment by Drjacky** [comment]
@GuilhE Same PR, on Android API **29** , X86_64,
Camera: Failed to Create camera file image
Gallery: Failed to crop the image
Screen Shot 2021-04-21 at 20 57 46

Screen Shot 2021-04-21 at 20 57 33

**Comment by Drjacky** [comment]
@GuilhE To fix the camera issue on API 29, I've changed the `getCameraDirectory` method to:
```kotlin
    private fun getCameraDirectory(context: Context): File {
        val dir =
            context.getExternalFilesDir(Environment.DIRECTORY_DCIM)// Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM)
        return File(dir, "Camera")
    }
```

Now, the camera works on API 29 but, Gallery has the issue!
The root of the issue is here:
```kotlin
private val galleryLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
            if (it.resultCode == Activity.RESULT_OK) {
```

`it.resultCode` is 0 while we're waiting for -1(`Activity.RESULT_OK`)

**Pull request closed without merging**
